from django.urls import path
from .views import (
    LoginView, UserProfileView, UserListCreateView, UserAssignRoleView,
    WarehouseListCreateView, WarehouseDetailView, WarehouseProductsView,
    CategoryListCreateView, CategoryDetailView,
    ProductListCreateView, ProductDetailView,
    StockIncomeOutcomeView, StockMovementsView, StockBalanceView, LowStockView,
    TransferListCreateView, TransferDetailView,
    OrderListCreateView, OrderDetailView,
    InventoryListCreateView, InventoryDetailView,
    NotificationListCreateView, StockBalanceCSVView, AuditLogView, AnalyticsView
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='login'),
    path('users/me/', UserProfileView.as_view(), name='user_profile'),
    path('users/', UserListCreateView.as_view(), name='user_list_create'),
    path('users/<int:pk>/assign-role/', UserAssignRoleView.as_view(), name='user_assign_role'),
    path('warehouses/', WarehouseListCreateView.as_view(), name='warehouse_list_create'),
    path('warehouses/<int:pk>/', WarehouseDetailView.as_view(), name='warehouse_detail'),
    path('warehouses/<int:pk>/products/', WarehouseProductsView.as_view(), name='warehouse_products'),
    path('categories/', CategoryListCreateView.as_view(), name='category_list_create'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('products/', ProductListCreateView.as_view(), name='product_list_create'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('stock/income-outcome/', StockIncomeOutcomeView.as_view(), name='stock_income_outcome'),
    path('stock/movements/', StockMovementsView.as_view(), name='stock_movements'),
    path('stock/movements/<int:product_id>/', StockMovementsView.as_view(), name='stock_movements_product'),
    path('stock/balance/', StockBalanceView.as_view(), name='stock_balance'),
    path('stock/balance/<int:product_id>/', StockBalanceView.as_view(), name='stock_balance_product'),
    path('products/low-stock/', LowStockView.as_view(), name='low_stock'),
    path('stock/transfers/', TransferListCreateView.as_view(), name='transfer_list_create'),
    path('stock/transfers/<int:pk>/', TransferDetailView.as_view(), name='transfer_detail'),
    path('orders/', OrderListCreateView.as_view(), name='order_list_create'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('inventory/', InventoryListCreateView.as_view(), name='inventory_list_create'),
    path('inventory/<int:pk>/', InventoryDetailView.as_view(), name='inventory_detail'),
    path('notifications/', NotificationListCreateView.as_view(), name='notification_list_create'),
    path('stock/balance/csv/', StockBalanceCSVView.as_view(), name='stock_balance_csv'),
    path('audit/', AuditLogView.as_view(), name='audit_log'),
    path('analytics/', AnalyticsView.as_view(), name='analytics'),
]