# Generated by Django 4.1.7 on 2025-06-23 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbalance',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='warehouse.category', verbose_name='Parent Category'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('order', 'Order'), ('inventory', 'Inventory'), ('general', 'General')], default='general', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
