# Generated by Django 4.1.7 on 2025-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('clerk', 'Clerk'), ('warehouse_manager', 'Warehouse Manager'), ('logistician', 'Logistician'), ('analyst', 'Analyst')], default='clerk', max_length=50),
        ),
    ]
